//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LDCSchema">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="schemaFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LDCProjection">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="projectionFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="projectionSource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LDCTaxonomy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="taxonomyFileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="applyAt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ldcSchema",
    "ldcProjection",
    "ldcTaxonomy"
})
@XmlRootElement(name = "ApplyLDCConfig")
public class ApplyLDCConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LDCSchema", required = true)
    protected LDCSchema ldcSchema;
    @XmlElement(name = "LDCProjection", required = true)
    protected LDCProjection ldcProjection;
    @XmlElement(name = "LDCTaxonomy", required = true)
    protected LDCTaxonomy ldcTaxonomy;
    @XmlAttribute(name = "applyAt")
    protected String applyAt;
    @XmlAttribute(name = "sequence")
    protected Byte sequence;

    /**
     * Gets the value of the ldcSchema property.
     * 
     * @return
     *     possible object is
     *     {@link LDCSchema }
     *     
     */
    public LDCSchema getLDCSchema() {
        return ldcSchema;
    }

    /**
     * Sets the value of the ldcSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link LDCSchema }
     *     
     */
    public void setLDCSchema(LDCSchema value) {
        this.ldcSchema = value;
    }

    /**
     * Gets the value of the ldcProjection property.
     * 
     * @return
     *     possible object is
     *     {@link LDCProjection }
     *     
     */
    public LDCProjection getLDCProjection() {
        return ldcProjection;
    }

    /**
     * Sets the value of the ldcProjection property.
     * 
     * @param value
     *     allowed object is
     *     {@link LDCProjection }
     *     
     */
    public void setLDCProjection(LDCProjection value) {
        this.ldcProjection = value;
    }

    /**
     * Gets the value of the ldcTaxonomy property.
     * 
     * @return
     *     possible object is
     *     {@link LDCTaxonomy }
     *     
     */
    public LDCTaxonomy getLDCTaxonomy() {
        return ldcTaxonomy;
    }

    /**
     * Sets the value of the ldcTaxonomy property.
     * 
     * @param value
     *     allowed object is
     *     {@link LDCTaxonomy }
     *     
     */
    public void setLDCTaxonomy(LDCTaxonomy value) {
        this.ldcTaxonomy = value;
    }

    /**
     * Gets the value of the applyAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplyAt() {
        return applyAt;
    }

    /**
     * Sets the value of the applyAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplyAt(String value) {
        this.applyAt = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSequence(Byte value) {
        this.sequence = value;
    }

}
