//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityField" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntityDefFile" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="DefType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="INLINE"/>
 *             &lt;enumeration value="Swager"/>
 *             &lt;enumeration value="JSONSchema"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityField",
    "entityDefFile"
})
public class EntityFields
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EntityField")
    protected List<EntityField> entityField;
    @XmlElement(name = "EntityDefFile")
    protected EntityDefFile entityDefFile;
    @XmlAttribute(name = "DefType", required = true)
    protected String defType;

    /**
     * Gets the value of the entityField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityField }
     * 
     * 
     */
    public List<EntityField> getEntityField() {
        if (entityField == null) {
            entityField = new ArrayList<EntityField>();
        }
        return this.entityField;
    }

    /**
     * Gets the value of the entityDefFile property.
     * 
     * @return
     *     possible object is
     *     {@link EntityDefFile }
     *     
     */
    public EntityDefFile getEntityDefFile() {
        return entityDefFile;
    }

    /**
     * Sets the value of the entityDefFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityDefFile }
     *     
     */
    public void setEntityDefFile(EntityDefFile value) {
        this.entityDefFile = value;
    }

    /**
     * Gets the value of the defType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefType() {
        return defType;
    }

    /**
     * Sets the value of the defType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefType(String value) {
        this.defType = value;
    }

}
