//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityFields">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EntityField" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EntityDefFile" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="filename" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="DefType" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="INLINE"/>
 *                       &lt;enumeration value="Swager"/>
 *                       &lt;enumeration value="JSONSchema"/>
 *                       &lt;minLength value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="collectionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="collectionType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntityMetadata" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MetadataField" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="entityFieldNameRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="readOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="searchable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="maxLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="minLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityFields",
    "entityCollection",
    "entityMetadata"
})
public class EntityDef
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EntityFields", required = true)
    protected EntityFields entityFields;
    @XmlElement(name = "EntityCollection")
    protected EntityCollection entityCollection;
    @XmlElement(name = "EntityMetadata")
    protected EntityMetadata entityMetadata;

    /**
     * Gets the value of the entityFields property.
     * 
     * @return
     *     possible object is
     *     {@link EntityFields }
     *     
     */
    public EntityFields getEntityFields() {
        return entityFields;
    }

    /**
     * Sets the value of the entityFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityFields }
     *     
     */
    public void setEntityFields(EntityFields value) {
        this.entityFields = value;
    }

    /**
     * Gets the value of the entityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link EntityCollection }
     *     
     */
    public EntityCollection getEntityCollection() {
        return entityCollection;
    }

    /**
     * Sets the value of the entityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityCollection }
     *     
     */
    public void setEntityCollection(EntityCollection value) {
        this.entityCollection = value;
    }

    /**
     * Gets the value of the entityMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link EntityMetadata }
     *     
     */
    public EntityMetadata getEntityMetadata() {
        return entityMetadata;
    }

    /**
     * Sets the value of the entityMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityMetadata }
     *     
     */
    public void setEntityMetadata(EntityMetadata value) {
        this.entityMetadata = value;
    }

}
