//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}LDCResponseConfigs" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
public class EntityRestResponse
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LDCResponseConfigs")
    protected LDCResponseConfigs ldcResponseConfigs;

    /**
     * Gets the value of the ldcResponseConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link LDCResponseConfigs }
     *     
     */
    public LDCResponseConfigs getLDCResponseConfigs() {
        return ldcResponseConfigs;
    }

    /**
     * Sets the value of the ldcResponseConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link LDCResponseConfigs }
     *     
     */
    public void setLDCResponseConfigs(LDCResponseConfigs value) {
        this.ldcResponseConfigs = value;
    }

}
