//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityBaseRestURL">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="sslRequried" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="true"/>
 *                       &lt;enumeration value="false"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="isAuthenticated" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SSLConfig" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="SSLFilePath">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="keyPassword">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AuthenticationConfig" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="BasicAuthentication" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="UserName">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Password">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityBaseRestURL",
    "sslConfig",
    "authenticationConfig"
})
public class EntityRestConfig
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EntityBaseRestURL", required = true)
    protected EntityBaseRestURL entityBaseRestURL;
    @XmlElement(name = "SSLConfig")
    protected SSLConfig sslConfig;
    @XmlElement(name = "AuthenticationConfig")
    protected AuthenticationConfig authenticationConfig;

    /**
     * Gets the value of the entityBaseRestURL property.
     * 
     * @return
     *     possible object is
     *     {@link EntityBaseRestURL }
     *     
     */
    public EntityBaseRestURL getEntityBaseRestURL() {
        return entityBaseRestURL;
    }

    /**
     * Sets the value of the entityBaseRestURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityBaseRestURL }
     *     
     */
    public void setEntityBaseRestURL(EntityBaseRestURL value) {
        this.entityBaseRestURL = value;
    }

    /**
     * Gets the value of the sslConfig property.
     * 
     * @return
     *     possible object is
     *     {@link SSLConfig }
     *     
     */
    public SSLConfig getSSLConfig() {
        return sslConfig;
    }

    /**
     * Sets the value of the sslConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link SSLConfig }
     *     
     */
    public void setSSLConfig(SSLConfig value) {
        this.sslConfig = value;
    }

    /**
     * Gets the value of the authenticationConfig property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationConfig }
     *     
     */
    public AuthenticationConfig getAuthenticationConfig() {
        return authenticationConfig;
    }

    /**
     * Sets the value of the authenticationConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationConfig }
     *     
     */
    public void setAuthenticationConfig(AuthenticationConfig value) {
        this.authenticationConfig = value;
    }

}
