//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EntityReadKeysMapping" minOccurs="0"/>
 *         &lt;element name="EntityRestRequest">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="EntityRestRequestHeaders" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EntityRestRequestHeader" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="entityKey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EntityRestRequestBody">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="TransformationConfig" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="LDCRequestConfigs" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;all>
 *                                       &lt;element ref="{}ApplyLDCConfig" minOccurs="0"/>
 *                                     &lt;/all>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="RequestBody" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                           &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="contentType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntityRestResponse" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{}LDCResponseConfigs" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="accessType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="authorizedResource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serviceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accessMethod" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serviceMethod" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entityReadKeysMapping",
    "entityRestRequest",
    "entityRestResponse"
})
public class EntityRestAccess
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EntityReadKeysMapping")
    protected EntityReadKeysMapping entityReadKeysMapping;
    @XmlElement(name = "EntityRestRequest", required = true)
    protected EntityRestRequest entityRestRequest;
    @XmlElement(name = "EntityRestResponse")
    protected EntityRestResponse entityRestResponse;
    @XmlAttribute(name = "accessType", required = true)
    protected String accessType;
    @XmlAttribute(name = "authorizedResource", required = true)
    protected String authorizedResource;
    @XmlAttribute(name = "serviceName", required = true)
    protected String serviceName;
    @XmlAttribute(name = "accessMethod", required = true)
    protected String accessMethod;
    @XmlAttribute(name = "serviceMethod", required = true)
    protected String serviceMethod;

    /**
     * Gets the value of the entityReadKeysMapping property.
     * 
     * @return
     *     possible object is
     *     {@link EntityReadKeysMapping }
     *     
     */
    public EntityReadKeysMapping getEntityReadKeysMapping() {
        return entityReadKeysMapping;
    }

    /**
     * Sets the value of the entityReadKeysMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityReadKeysMapping }
     *     
     */
    public void setEntityReadKeysMapping(EntityReadKeysMapping value) {
        this.entityReadKeysMapping = value;
    }

    /**
     * Gets the value of the entityRestRequest property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRestRequest }
     *     
     */
    public EntityRestRequest getEntityRestRequest() {
        return entityRestRequest;
    }

    /**
     * Sets the value of the entityRestRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRestRequest }
     *     
     */
    public void setEntityRestRequest(EntityRestRequest value) {
        this.entityRestRequest = value;
    }

    /**
     * Gets the value of the entityRestResponse property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRestResponse }
     *     
     */
    public EntityRestResponse getEntityRestResponse() {
        return entityRestResponse;
    }

    /**
     * Sets the value of the entityRestResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRestResponse }
     *     
     */
    public void setEntityRestResponse(EntityRestResponse value) {
        this.entityRestResponse = value;
    }

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessType(String value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the authorizedResource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedResource() {
        return authorizedResource;
    }

    /**
     * Sets the value of the authorizedResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedResource(String value) {
        this.authorizedResource = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the accessMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessMethod() {
        return accessMethod;
    }

    /**
     * Sets the value of the accessMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessMethod(String value) {
        this.accessMethod = value;
    }

    /**
     * Gets the value of the serviceMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceMethod() {
        return serviceMethod;
    }

    /**
     * Sets the value of the serviceMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceMethod(String value) {
        this.serviceMethod = value;
    }

}
