//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="TransformationConfig" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="fileName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LDCRequestConfigs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element ref="{}ApplyLDCConfig" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RequestBody" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
public class EntityRestRequestBody
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TransformationConfig")
    protected TransformationConfig transformationConfig;
    @XmlElement(name = "LDCRequestConfigs")
    protected LDCRequestConfigs ldcRequestConfigs;
    @XmlElement(name = "RequestBody")
    protected String requestBody;
    @XmlAttribute(name = "source", required = true)
    protected String source;

    /**
     * Gets the value of the transformationConfig property.
     * 
     * @return
     *     possible object is
     *     {@link TransformationConfig }
     *     
     */
    public TransformationConfig getTransformationConfig() {
        return transformationConfig;
    }

    /**
     * Sets the value of the transformationConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformationConfig }
     *     
     */
    public void setTransformationConfig(TransformationConfig value) {
        this.transformationConfig = value;
    }

    /**
     * Gets the value of the ldcRequestConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link LDCRequestConfigs }
     *     
     */
    public LDCRequestConfigs getLDCRequestConfigs() {
        return ldcRequestConfigs;
    }

    /**
     * Sets the value of the ldcRequestConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link LDCRequestConfigs }
     *     
     */
    public void setLDCRequestConfigs(LDCRequestConfigs value) {
        this.ldcRequestConfigs = value;
    }

    /**
     * Gets the value of the requestBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * Sets the value of the requestBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestBody(String value) {
        this.requestBody = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

}
