//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetadataField" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="entityFieldNameRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="readOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="searchable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="maxLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="minLength" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataField"
})
public class EntityMetadata
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MetadataField")
    protected List<MetadataField> metadataField;

    /**
     * Gets the value of the metadataField property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataField property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataField }
     * 
     * 
     */
    public List<MetadataField> getMetadataField() {
        if (metadataField == null) {
            metadataField = new ArrayList<MetadataField>();
        }
        return this.metadataField;
    }

}
