//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}EntityReadKeysMapping" minOccurs="0"/>
 *         &lt;element name="EntityUpdateKeysMapping" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}EntityKey" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntityFilterKeysMapping" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}EntityKey" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EntityInsertKeysMapping" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}EntityKey" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}LDCResponseConfigs" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="accessType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="authorizedResource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isCollection" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="accessMethod" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
public class EntityAccess
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EntityReadKeysMapping")
    protected EntityReadKeysMapping entityReadKeysMapping;
    @XmlElement(name = "EntityUpdateKeysMapping")
    protected EntityUpdateKeysMapping entityUpdateKeysMapping;
    @XmlElement(name = "EntityFilterKeysMapping")
    protected EntityFilterKeysMapping entityFilterKeysMapping;
    @XmlElement(name = "EntityInsertKeysMapping")
    protected EntityInsertKeysMapping entityInsertKeysMapping;
    @XmlElement(name = "LDCResponseConfigs")
    protected LDCResponseConfigs ldcResponseConfigs;
    @XmlAttribute(name = "accessType", required = true)
    protected String accessType;
    @XmlAttribute(name = "authorizedResource", required = true)
    protected String authorizedResource;
    @XmlAttribute(name = "isCollection")
    protected Boolean isCollection;
    @XmlAttribute(name = "accessMethod", required = true)
    protected String accessMethod;

    /**
     * Gets the value of the entityReadKeysMapping property.
     * 
     * @return
     *     possible object is
     *     {@link EntityReadKeysMapping }
     *     
     */
    public EntityReadKeysMapping getEntityReadKeysMapping() {
        return entityReadKeysMapping;
    }

    /**
     * Sets the value of the entityReadKeysMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityReadKeysMapping }
     *     
     */
    public void setEntityReadKeysMapping(EntityReadKeysMapping value) {
        this.entityReadKeysMapping = value;
    }

    /**
     * Gets the value of the entityUpdateKeysMapping property.
     * 
     * @return
     *     possible object is
     *     {@link EntityUpdateKeysMapping }
     *     
     */
    public EntityUpdateKeysMapping getEntityUpdateKeysMapping() {
        return entityUpdateKeysMapping;
    }

    /**
     * Sets the value of the entityUpdateKeysMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityUpdateKeysMapping }
     *     
     */
    public void setEntityUpdateKeysMapping(EntityUpdateKeysMapping value) {
        this.entityUpdateKeysMapping = value;
    }

    /**
     * Gets the value of the entityFilterKeysMapping property.
     * 
     * @return
     *     possible object is
     *     {@link EntityFilterKeysMapping }
     *     
     */
    public EntityFilterKeysMapping getEntityFilterKeysMapping() {
        return entityFilterKeysMapping;
    }

    /**
     * Sets the value of the entityFilterKeysMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityFilterKeysMapping }
     *     
     */
    public void setEntityFilterKeysMapping(EntityFilterKeysMapping value) {
        this.entityFilterKeysMapping = value;
    }

    /**
     * Gets the value of the entityInsertKeysMapping property.
     * 
     * @return
     *     possible object is
     *     {@link EntityInsertKeysMapping }
     *     
     */
    public EntityInsertKeysMapping getEntityInsertKeysMapping() {
        return entityInsertKeysMapping;
    }

    /**
     * Sets the value of the entityInsertKeysMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityInsertKeysMapping }
     *     
     */
    public void setEntityInsertKeysMapping(EntityInsertKeysMapping value) {
        this.entityInsertKeysMapping = value;
    }

    /**
     * Gets the value of the ldcResponseConfigs property.
     * 
     * @return
     *     possible object is
     *     {@link LDCResponseConfigs }
     *     
     */
    public LDCResponseConfigs getLDCResponseConfigs() {
        return ldcResponseConfigs;
    }

    /**
     * Sets the value of the ldcResponseConfigs property.
     * 
     * @param value
     *     allowed object is
     *     {@link LDCResponseConfigs }
     *     
     */
    public void setLDCResponseConfigs(LDCResponseConfigs value) {
        this.ldcResponseConfigs = value;
    }

    /**
     * Gets the value of the accessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessType(String value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the authorizedResource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizedResource() {
        return authorizedResource;
    }

    /**
     * Sets the value of the authorizedResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizedResource(String value) {
        this.authorizedResource = value;
    }

    /**
     * Gets the value of the isCollection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsCollection() {
        if (isCollection == null) {
            return false;
        } else {
            return isCollection;
        }
    }

    /**
     * Sets the value of the isCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCollection(Boolean value) {
        this.isCollection = value;
    }

    /**
     * Gets the value of the accessMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessMethod() {
        return accessMethod;
    }

    /**
     * Sets the value of the accessMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessMethod(String value) {
        this.accessMethod = value;
    }

}
