//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.28 at 10:47:27 AM IST 
//


package com.attunedlabs.leapentity.config.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="required" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="projectionFileName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="projectionSource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class LDCProjection
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "required", required = true)
    protected boolean required;
    @XmlAttribute(name = "projectionFileName")
    protected String projectionFileName;
    @XmlAttribute(name = "projectionSource")
    protected String projectionSource;

    /**
     * Gets the value of the required property.
     * 
     */
    public boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     */
    public void setRequired(boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the projectionFileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectionFileName() {
        return projectionFileName;
    }

    /**
     * Sets the value of the projectionFileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectionFileName(String value) {
        this.projectionFileName = value;
    }

    /**
     * Gets the value of the projectionSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectionSource() {
        return projectionSource;
    }

    /**
     * Sets the value of the projectionSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectionSource(String value) {
        this.projectionSource = value;
    }

}
