//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.24 at 11:02:24 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://attunedlabs.com/internal/FeatureMetaInfoSupporting")
package com.attunedlabs.featuremetainfo.jaxb;
