//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.24 at 11:02:24 AM IST 
//


package com.attunedlabs.featuremetainfo.jaxb;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HandlerConfiguration" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="resourceName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "handlerConfiguration"
})
@XmlRootElement(name = "ServiceHandlerConfiguration")
public class ServiceHandlerConfiguration
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "HandlerConfiguration", namespace = "http://attunedlabs.com/internal/FeatureMetaInfoSupporting")
    protected HandlerConfiguration handlerConfiguration;

    /**
     * Gets the value of the handlerConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link HandlerConfiguration }
     *     
     */
    public HandlerConfiguration getHandlerConfiguration() {
        return handlerConfiguration;
    }

    /**
     * Sets the value of the handlerConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlerConfiguration }
     *     
     */
    public void setHandlerConfiguration(HandlerConfiguration value) {
        this.handlerConfiguration = value;
    }

}
