//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.27 at 03:45:33 PM IST 
//


package com.attunedlabs.applicationservicehandlers.config.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.attunedlabs.applicationservicehandlers.config.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.attunedlabs.applicationservicehandlers.config.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration }
     * 
     */
    public ApplicationServiceHandlerConfiguration createApplicationServiceHandlerConfiguration() {
        return new ApplicationServiceHandlerConfiguration();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.CommonServiceHandler }
     * 
     */
    public ApplicationServiceHandlerConfiguration.CommonServiceHandler createApplicationServiceHandlerConfigurationCommonServiceHandler() {
        return new ApplicationServiceHandlerConfiguration.CommonServiceHandler();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation }
     * 
     */
    public ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation createApplicationServiceHandlerConfigurationFeatureServiceHandlerServiceHandlerHandlerImplementation() {
        return new ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler }
     * 
     */
    public ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler createApplicationServiceHandlerConfigurationFeatureServiceHandlerServiceHandler() {
        return new ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler }
     * 
     */
    public ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler createApplicationServiceHandlerConfigurationCommonServiceHandlerServiceHandler() {
        return new ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.HandlerImplementation }
     * 
     */
    public ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.HandlerImplementation createApplicationServiceHandlerConfigurationCommonServiceHandlerServiceHandlerHandlerImplementation() {
        return new ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.HandlerImplementation();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.ExcludedServices }
     * 
     */
    public ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.ExcludedServices createApplicationServiceHandlerConfigurationCommonServiceHandlerServiceHandlerExcludedServices() {
        return new ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.ExcludedServices();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices }
     * 
     */
    public ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices createApplicationServiceHandlerConfigurationFeatureServiceHandlerServiceHandlerIncludedServices() {
        return new ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.FeatureServiceHandler }
     * 
     */
    public ApplicationServiceHandlerConfiguration.FeatureServiceHandler createApplicationServiceHandlerConfigurationFeatureServiceHandler() {
        return new ApplicationServiceHandlerConfiguration.FeatureServiceHandler();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service }
     * 
     */
    public ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service createApplicationServiceHandlerConfigurationFeatureServiceHandlerServiceHandlerIncludedServicesService() {
        return new ApplicationServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service();
    }

    /**
     * Create an instance of {@link ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.ExcludedServices.Service }
     * 
     */
    public ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.ExcludedServices.Service createApplicationServiceHandlerConfigurationCommonServiceHandlerServiceHandlerExcludedServicesService() {
        return new ApplicationServiceHandlerConfiguration.CommonServiceHandler.ServiceHandler.ExcludedServices.Service();
    }

}
