//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.05 at 10:48:01 AM IST 
//


package com.attunedlabs.applicationmetainfo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ApplicationServiceHandlers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServiceHandlerConfig" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="resourceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "App-Metainfo")
public class AppMetainfo {

    @XmlElement(name = "ApplicationServiceHandlers")
    protected AppMetainfo.ApplicationServiceHandlers applicationServiceHandlers;

    /**
     * Gets the value of the applicationServiceHandlers property.
     * 
     * @return
     *     possible object is
     *     {@link AppMetainfo.ApplicationServiceHandlers }
     *     
     */
    public AppMetainfo.ApplicationServiceHandlers getApplicationServiceHandlers() {
        return applicationServiceHandlers;
    }

    /**
     * Sets the value of the applicationServiceHandlers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppMetainfo.ApplicationServiceHandlers }
     *     
     */
    public void setApplicationServiceHandlers(AppMetainfo.ApplicationServiceHandlers value) {
        this.applicationServiceHandlers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ServiceHandlerConfig" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="resourceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "serviceHandlerConfig"
    })
    public static class ApplicationServiceHandlers {

        @XmlElement(name = "ServiceHandlerConfig")
        protected AppMetainfo.ApplicationServiceHandlers.ServiceHandlerConfig serviceHandlerConfig;

        /**
         * Gets the value of the serviceHandlerConfig property.
         * 
         * @return
         *     possible object is
         *     {@link AppMetainfo.ApplicationServiceHandlers.ServiceHandlerConfig }
         *     
         */
        public AppMetainfo.ApplicationServiceHandlers.ServiceHandlerConfig getServiceHandlerConfig() {
            return serviceHandlerConfig;
        }

        /**
         * Sets the value of the serviceHandlerConfig property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppMetainfo.ApplicationServiceHandlers.ServiceHandlerConfig }
         *     
         */
        public void setServiceHandlerConfig(AppMetainfo.ApplicationServiceHandlers.ServiceHandlerConfig value) {
            this.serviceHandlerConfig = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="resourceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class ServiceHandlerConfig {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "resourceName", required = true)
            protected String resourceName;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the resourceName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResourceName() {
                return resourceName;
            }

            /**
             * Sets the value of the resourceName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResourceName(String value) {
                this.resourceName = value;
            }

        }

    }

}
