//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.27 at 03:47:26 PM IST 
//


package com.attunedlabs.servicehandlers.config.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.attunedlabs.servicehandlers.config.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.attunedlabs.servicehandlers.config.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceHandlerConfiguration }
     * 
     */
    public ServiceHandlerConfiguration createServiceHandlerConfiguration() {
        return new ServiceHandlerConfiguration();
    }

    /**
     * Create an instance of {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation }
     * 
     */
    public ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation createServiceHandlerConfigurationFeatureServiceHandlerServiceHandlerHandlerImplementation() {
        return new ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation();
    }

    /**
     * Create an instance of {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices }
     * 
     */
    public ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices createServiceHandlerConfigurationFeatureServiceHandlerServiceHandlerIncludedServices() {
        return new ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices();
    }

    /**
     * Create an instance of {@link ServiceHandlerConfiguration.FeatureServiceHandler }
     * 
     */
    public ServiceHandlerConfiguration.FeatureServiceHandler createServiceHandlerConfigurationFeatureServiceHandler() {
        return new ServiceHandlerConfiguration.FeatureServiceHandler();
    }

    /**
     * Create an instance of {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler }
     * 
     */
    public ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler createServiceHandlerConfigurationFeatureServiceHandlerServiceHandler() {
        return new ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler();
    }

    /**
     * Create an instance of {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service }
     * 
     */
    public ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service createServiceHandlerConfigurationFeatureServiceHandlerServiceHandlerIncludedServicesService() {
        return new ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service();
    }

}
