//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.27 at 03:47:26 PM IST 
//

package com.attunedlabs.servicehandlers.config.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="FeatureServiceHandler">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServiceHandler" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="HandlerImplementation">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="HandlerConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="beanId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="fqcn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="IncludedServices">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="featureGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="featureName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="serviceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" default="*">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="pre-service"/>
 *                                 &lt;enumeration value="post-service"/>
 *                                 &lt;enumeration value="*"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="execute" default="sync">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="sync"/>
 *                                 &lt;enumeration value="async"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ServiceHandlerConfiguration")
public class ServiceHandlerConfiguration {

	@XmlElement(name = "FeatureServiceHandler", required = true)
	protected ServiceHandlerConfiguration.FeatureServiceHandler featureServiceHandler;

	/**
	 * Gets the value of the featureServiceHandler property.
	 * 
	 * @return possible object is
	 *         {@link ServiceHandlerConfiguration.FeatureServiceHandler }
	 * 
	 */
	public ServiceHandlerConfiguration.FeatureServiceHandler getFeatureServiceHandler() {
		return featureServiceHandler;
	}

	/**
	 * Sets the value of the featureServiceHandler property.
	 * 
	 * @param value
	 *            allowed object is
	 *            {@link ServiceHandlerConfiguration.FeatureServiceHandler }
	 * 
	 */
	public void setFeatureServiceHandler(ServiceHandlerConfiguration.FeatureServiceHandler value) {
		this.featureServiceHandler = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ServiceHandler" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="HandlerImplementation">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="HandlerConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                           &lt;attribute name="beanId" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                           &lt;attribute name="fqcn" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                   &lt;element name="IncludedServices">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
	 *                               &lt;complexType>
	 *                                 &lt;simpleContent>
	 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                                     &lt;attribute name="featureGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                                     &lt;attribute name="featureName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                                     &lt;attribute name="serviceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                                   &lt;/extension>
	 *                                 &lt;/simpleContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *                 &lt;attribute name="type" default="*">
	 *                   &lt;simpleType>
	 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *                       &lt;enumeration value="pre-service"/>
	 *                       &lt;enumeration value="post-service"/>
	 *                       &lt;enumeration value="*"/>
	 *                     &lt;/restriction>
	 *                   &lt;/simpleType>
	 *                 &lt;/attribute>
	 *                 &lt;attribute name="execute" default="sync">
	 *                   &lt;simpleType>
	 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *                       &lt;enumeration value="sync"/>
	 *                       &lt;enumeration value="async"/>
	 *                     &lt;/restriction>
	 *                   &lt;/simpleType>
	 *                 &lt;/attribute>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "serviceHandler" })
	public static class FeatureServiceHandler {

		@XmlElement(name = "ServiceHandler")
		protected List<ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler> serviceHandler;

		/**
		 * Gets the value of the serviceHandler property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the serviceHandler property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getServiceHandler().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler }
		 * 
		 * 
		 */
		public List<ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler> getServiceHandler() {
			if (serviceHandler == null) {
				serviceHandler = new ArrayList<ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler>();
			}
			return this.serviceHandler;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="HandlerImplementation">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="HandlerConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *                 &lt;attribute name="beanId" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                 &lt;attribute name="fqcn" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *         &lt;element name="IncludedServices">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
		 *                     &lt;complexType>
		 *                       &lt;simpleContent>
		 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *                           &lt;attribute name="featureGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                           &lt;attribute name="featureName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                           &lt;attribute name="serviceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *                         &lt;/extension>
		 *                       &lt;/simpleContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *       &lt;attribute name="type" default="*">
		 *         &lt;simpleType>
		 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
		 *             &lt;enumeration value="pre-service"/>
		 *             &lt;enumeration value="post-service"/>
		 *             &lt;enumeration value="*"/>
		 *           &lt;/restriction>
		 *         &lt;/simpleType>
		 *       &lt;/attribute>
		 *       &lt;attribute name="execute" default="sync">
		 *         &lt;simpleType>
		 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
		 *             &lt;enumeration value="sync"/>
		 *             &lt;enumeration value="async"/>
		 *           &lt;/restriction>
		 *         &lt;/simpleType>
		 *       &lt;/attribute>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "description", "handlerImplementation", "includedServices" })
		public static class ServiceHandler {

			@XmlElement(name = "Description", required = true)
			protected String description;
			@XmlElement(name = "HandlerImplementation", required = true)
			protected ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation handlerImplementation;
			@XmlElement(name = "IncludedServices", required = true)
			protected ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices includedServices;
			@XmlAttribute(name = "type")
			protected String type;
			@XmlAttribute(name = "execute")
			protected String execute;
			@XmlAttribute(name = "handlerId")
			protected String handlerId;

			public String getHandlerId() {
				return handlerId;
			}

			public void setHandlerId(String handlerId) {
				this.handlerId = handlerId;
			}

			/**
			 * Gets the value of the description property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getDescription() {
				return description;
			}

			/**
			 * Sets the value of the description property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setDescription(String value) {
				this.description = value;
			}

			/**
			 * Gets the value of the handlerImplementation property.
			 * 
			 * @return possible object is
			 *         {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation }
			 * 
			 */
			public ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation getHandlerImplementation() {
				return handlerImplementation;
			}

			/**
			 * Sets the value of the handlerImplementation property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation }
			 * 
			 */
			public void setHandlerImplementation(
					ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.HandlerImplementation value) {
				this.handlerImplementation = value;
			}

			/**
			 * Gets the value of the includedServices property.
			 * 
			 * @return possible object is
			 *         {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices }
			 * 
			 */
			public ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices getIncludedServices() {
				return includedServices;
			}

			/**
			 * Sets the value of the includedServices property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices }
			 * 
			 */
			public void setIncludedServices(
					ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices value) {
				this.includedServices = value;
			}

			/**
			 * Gets the value of the type property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getType() {
				if (type == null) {
					return "*";
				} else {
					return type;
				}
			}

			/**
			 * Sets the value of the type property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setType(String value) {
				this.type = value;
			}

			/**
			 * Gets the value of the execute property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getExecute() {
				if (execute == null) {
					return "sync";
				} else {
					return execute;
				}
			}

			/**
			 * Sets the value of the execute property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setExecute(String value) {
				this.execute = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="HandlerConfig" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *       &lt;attribute name="beanId" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *       &lt;attribute name="fqcn" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "handlerConfig" })
			public static class HandlerImplementation {

				@XmlElement(name = "HandlerConfig", required = true)
				protected String handlerConfig;
				@XmlAttribute(name = "beanId")
				protected String beanId;
				@XmlAttribute(name = "fqcn")
				protected String fqcn;

				/**
				 * Gets the value of the handlerConfig property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getHandlerConfig() {
					return handlerConfig;
				}

				/**
				 * Sets the value of the handlerConfig property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setHandlerConfig(String value) {
					this.handlerConfig = value;
				}

				/**
				 * Gets the value of the beanId property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getBeanId() {
					return beanId;
				}

				/**
				 * Sets the value of the beanId property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setBeanId(String value) {
					this.beanId = value;
				}

				/**
				 * Gets the value of the fqcn property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getFqcn() {
					return fqcn;
				}

				/**
				 * Sets the value of the fqcn property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setFqcn(String value) {
					this.fqcn = value;
				}

			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
			 *           &lt;complexType>
			 *             &lt;simpleContent>
			 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
			 *                 &lt;attribute name="featureGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *                 &lt;attribute name="featureName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *                 &lt;attribute name="serviceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
			 *               &lt;/extension>
			 *             &lt;/simpleContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "service" })
			public static class IncludedServices {

				@XmlElement(name = "Service")
				protected List<ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service> service;

				/**
				 * Gets the value of the service property.
				 * 
				 * <p>
				 * This accessor method returns a reference to the live list,
				 * not a snapshot. Therefore any modification you make to the
				 * returned list will be present inside the JAXB object. This is
				 * why there is not a <CODE>set</CODE> method for the service
				 * property.
				 * 
				 * <p>
				 * For example, to add a new item, do as follows:
				 * 
				 * <pre>
				 * getService().add(newItem);
				 * </pre>
				 * 
				 * 
				 * <p>
				 * Objects of the following type(s) are allowed in the list
				 * {@link ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service }
				 * 
				 * 
				 */
				public List<ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service> getService() {
					if (service == null) {
						service = new ArrayList<ServiceHandlerConfiguration.FeatureServiceHandler.ServiceHandler.IncludedServices.Service>();
					}
					return this.service;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;simpleContent>
				 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
				 *       &lt;attribute name="featureGroup" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
				 *       &lt;attribute name="featureName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
				 *       &lt;attribute name="serviceName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
				 *     &lt;/extension>
				 *   &lt;/simpleContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "value" })
				public static class Service {

					@XmlValue
					protected String value;
					@XmlAttribute(name = "featureGroup", required = true)
					protected String featureGroup;
					@XmlAttribute(name = "featureName", required = true)
					protected String featureName;
					@XmlAttribute(name = "serviceName", required = true)
					protected String serviceName;

					/**
					 * Gets the value of the value property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getValue() {
						return value;
					}

					/**
					 * Sets the value of the value property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setValue(String value) {
						this.value = value;
					}

					/**
					 * Gets the value of the featureGroup property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getFeatureGroup() {
						return featureGroup;
					}

					/**
					 * Sets the value of the featureGroup property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setFeatureGroup(String value) {
						this.featureGroup = value;
					}

					/**
					 * Gets the value of the featureName property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getFeatureName() {
						return featureName;
					}

					/**
					 * Sets the value of the featureName property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setFeatureName(String value) {
						this.featureName = value;
					}

					/**
					 * Gets the value of the serviceName property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getServiceName() {
						return serviceName;
					}

					/**
					 * Sets the value of the serviceName property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setServiceName(String value) {
						this.serviceName = value;
					}

				}

			}

		}

	}

}
