name: test CI with Maven build 

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name:  Run build script
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
        
    - name: Build with Maven
      run: attunedlabs/services/maven-build.bat
      #run: mvn -B package --file attunedlabs/services/leap-core/pom.xml
      shell: cmd
