name: Runner CI

on:
  workflow_dispatch:
  push:
    branches:
    - test
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - '**'
    paths-ignore:
    - '**.md'

jobs:
  build:
    strategy:
      matrix:
        runtime: [ win-x64, win-arm64 ]
        include:
        - runtime: win-x64
          os: windows-2019
          devScript: attunedlabs/services/maven-build.bat

        - runtime: win-arm64
          os: windows-latest
          devScript: attunedlabs/services/maven-build.bat

    runs-on:  windows-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}

    # Build runner layout
    - name: Build
      run: |
        ${{ matrix.devScript }} layout Release ${{ matrix.runtime }}
      working-directory: attunedlabs
    
