name: test CI with Maven build 

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name:  Run build script
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
        settings-path: ${{ github.workspace }}
        
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
      working-directory: attunedlabs
      #run: mvn clean install --file attunedlabs/services/leap-core/pom.xml
      #shell: pwsh
