name: Runner CI

on:
  workflow_dispatch:
  push:
    branches:
    - test
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - '**'
    paths-ignore:
    - '**.md'

jobs:
  build:
    strategy:
      matrix:
        runtime: [ linux-x64, linux-arm64, linux-arm, win-x64, win-arm64, osx-x64, osx-arm64 ]
        include:
        - runtime: win-x64
          os: windows-2019
          devScript: D:\a\actiontest\actiontest\attunedlabs/services/maven-build.bat

        - runtime: win-arm64
          os: windows-latest
          devScript: D:\a\actiontest\actiontest\attunedlabs/services/maven-build.bat

    runs-on:  windows-latest
    steps:
    - uses: actions/setup-java@v3

    # Build runner layout
    - name: Build
      run: |
        ${{ matrix.devScript }} layout Release ${{ matrix.runtime }}
      working-directory: D:\a\actiontest\actiontest\attunedlabs/services

    
